from datetime import date
import click
from base import Session, engine, Base
#from flask.cli import with_appcontext
import flask.cli

from models import User, Marca, Coche, Comentario

@main.cli.command('create_tables')
def create_tables():
    Base.metadata.drop_all(bind=engine, tables=[Coche.__table__])
    Base.metadata.drop_all(bind=engine, tables=[Marca.__table__])
    Base.metadata.drop_all(bind=engine, tables=[User.__table__])
    Base.metadata.drop_all(bind=engine, tables=[Comentario.__table__])
    Base.metadata.create_all(engine)

    session = Session()

    co1 = Comentario("Juan Pablo Nguema", "He vendido mi Fiat Uno Turbo en Bustomóviles y he de decir que son unos auténticos profesionales.")
    co2 = Comentario("Javier Clemente", "Estaba buscando algún lado en el que vender mi gabarra por falta de uso. Aquí no me la aceptaron, pero se quedaron con mi Mercedes.")
    co3 = Comentario("Elon Musk", "Compré aquí un Land Rover Defender de 1990 para utilizarlo como base del Tesla Cybertruck. Salió bien.")
    co4 = Comentario("Francesco Virgolini", "Me compré aquí un Alfa Romeo Giulia Quadrivoglio y es un coche que va de cine.")

    m1 = Marca("Ford", "EEUU") 
    m2 = Marca("Mercedes", "Alemania") 
    m3 = Marca("BMW", "Alemania") 
    m4 = Marca("Audi", "Alemania") 
    m5 = Marca("Renault", "Francia") 
    m6 = Marca("Volvo", "Suecia") 
    m7 = Marca("Toyota", "Japón") 

    c1 = Coche(m1, "Fiesta", 2004, 127500, "Gasolina", 80, "Ford Fiesta trend 1.4 gasolina del 2004 Con distintivo medio ambiental Pantalla táctil de 7 Rueda de recambio, dos llaves 127.500 km, se entrega con todas las revisiones hechas, ITV, etc...", 2300, "Bilbao", "https://www.anunciosmarinaalta.com/uploads/2012/01/ford-fiesta-tren-2003-para-vender-34572-2.jpg")
    c2 = Coche(m1, "Focus", 1999, 144200, "Gasolina", 100, "Ford focus sedan, bien cuidado, funciona perfectamente, poco kilometraje real, elevalunas eléctrico, cierre centralizado, aire acondicionado perfecto, llantas recién cambiadas, motor y caja perfecto,itv en vigor.", 1900, "Vitoria", "https://cdn.wallapop.com/images/10420/96/h2/__/c10420p555069191/i1661844235.jpg")
    c3 = Coche(m1, "Mondeo", 2001, 153404, "Gasolina", 125, "Único dueño. Mantenimiento al día. Vehículo amplio y espacioso, muy cuidado. Posibilidad de admitir vehículo como parte del pago. Garantía 12 meses (según condiciones). Se entregan vehículo en todo el territorio nacional (condiciones y costos a verificar) Coche en perfecto estado y totalmente revisado.", 1450, "Donostia", "https://img.milanuncios.com/fg/2943/29/294329457_1.jpg?VersionId=ugc6B6wwhoGwNroFnvoJUlIWaQzFcTmq")
    c4 = Coche(m2, "Clase C", 2004, 260000, "Diesel", 143, "Cambio automático Abs Srs 4 Airbags Faros antiniebla Cierre centralizado Climatizador bizona Dirección asistida 4 Elevalunas eléctricos Control de velocidad Asientos eléctricos Asientos calefactables Sensor de luces Retrovisores eléctricos Llantas de aleación Ordenador de abordo Volante multifunción Muy buen estado", 3800, "Donostia", "https://www.grupocompostela.com/Archivos/Fotos/Coches_fotos/mercedes_benz-clase_c-2002-segunda_mano-santiago-compostela-coruna-090516_15-146278994263.jpg")
    c5 = Coche(m2, "Clase E", 2002, 207563, "Gasolina", 224, "Considerada de las mejores generaciones de clase e de la historia, la w211 es también una de las que mejor ha mostrado la filosofía del modelo: confort, lujo y fiabilidad. esta unidad cuenta con histórico de mantenimiento a través de libro de revisiones y facturas. Su motor de 6 cilindros y 224 cv es muy equilibrado.", 4300, "Bilbao", "https://img.milanuncios.com/fg/2677/63/267763745_1.jpg?VersionId=blgaOpvVhvKs6pLWMb5rhH3FJPWsmONu")
    c6 = Coche(m2, "Clase E", 1988, 407000, "Diesel", 130, "Clásico, ITV pasada hasta junio 2021, funciona perfectamente, tiene algunas cositas para hacer por la edad", 2200, "Vitoria", "https://3.bp.blogspot.com/-xWmDpjooJaA/U4I7-qELT_I/AAAAAAAAFes/dqIgQXP2O3A/s1600/DSCF1627.JPG")
    c7 = Coche(m3, "Serie 3", 1987, 135000, "Gasolina", 150, "Bmw 325 e30 coupé automático, pack mtecnic exterior comprado en bmw . Libros de mantenimiento. Coche en perfecto Estado de mantenimiento. Misma familia. Primero con matrículas turistas.", 8450, "Donostia", "https://img.milanuncios.com/fg/3456/30/345630586_3.jpg?VersionId=8vaVJq9po2PBc4epwca1vSU3LWHgABSi")
    c8 = Coche(m3, "Serie 7", 2012, 188696, "Diesel", 258, "llantas de aleación ligera de radios dobles (estilo 648 m), cambio automático deportivo, cámara para marcha atrás, bmw display key, dispositivo de alarma con mando a distancia, acceso confort, paquete deportivo m, climatizador con regulación de 4 zonas", 22800, "Vitoria", "https://www.km77.com/images/medium/0/7/4/3/bms-serie-7-exterior-lateral.310743.jpg")
    c9 = Coche(m4, "A4", 2005, 305000, "Diesel", 140, "Coche en buen estado, correa distribución hecha hace poco, xenon, automatico con levas al volante y 7 marchas. Navegador de serie con conexion por bluetoth y TV. Equipo de sonido de serie con subwoofer en bandeja. Asientos de cuero color beige. Control de crucero. Pantalla ordenador de abordo a color.", 5150, "Bilbao", "https://img.milanuncios.com/fg/2626/21/262621972_3.jpg?VersionId=2WXcKInA5a6Lf2UVj_OUQwKnGi7gH1hn")
    c10 = Coche(m4, "A6", 2004, 152000, "Diesel", 130, "Vehículo en muy buen estado. ITV al día. Equipado con extras como: elevalunas eléctricos, climatizador, 3 llaves, cierre centralizado con mando a distancia, sensor trasero de aparcamiento, airbag etc. Para más información no dude en contactar.", 3490, "Donostia", "https://cdn.wallapop.com/images/10420/94/3z/__/c10420p551100626/i1643420527.jpg?pictureSize=W640")
    c11 = Coche(m3, "Serie 3", 1992, 235000, "Gasolina", 150, "Vehiculo nacional, primera matricula O-xxxx-BG 5/11/1992, 235.000km impecable estado, 2 juegos de llaves, todo original, itv recien pasada, todo al dia, aire acondicionado....todo funcionando perfectamente, mejor ver y probar.", 1500, "Bilbao", "https://periodismodelmotor.com/wp-content/uploads/2016/01/curiosidades-bmw-m3-e36-1280x720.jpg")
    c12 = Coche(m4, "A3", 2007, 278000, "Diesel", 110, "Motor 1.9 tdi 110cv. 278.000km reales y certificados. Garantía 12 meses ampliable a 24 con cobertura nacional y entrega a domicilio en toda españa. financia con nosotros desde 150€ al mes sin entrada. mantenimiento completo de los principales puntos de seguridad.", 4200, "Donostia", "https://cdn.wallapop.com/images/10420/5s/9v/__/c10420p349821156/i816465226.jpg?pictureSize=W640")
    c13 = Coche(m6, "480 Turbo", 1991, 117000, "Gasolina", 120, "Coche en buen estado. Actualmente de baja temporal. Se entregaría rehabilitado sin ITV. Funcionando casi todo. Tiene algún fallo subsanable. Precio negociable. También aceptaría algún cambio por coche más moderno ajustando diferencia.", 1300, "Bilbao", "https://img.milanuncios.com/fg/3287/21/328721514_3.jpg?VersionId=AQgNAbaCkhmGK5e5bMuPys8.y1BEPg0q")
    c14 = Coche(m6, "S80", 2001, 257000, "Gasolina", 170, "Volvo s80 motor atmosférico 170cv 5 cilindros, caja de cambios automática, con bola de remolque homologada en la ficha técnica, el coche se encuentra en un estado muy bueno, era coche oficial del cuerpo diplomático hasta el año 2014 y después ha tenido un único dueño hasta hoy, al coche le funciona todo perfectamente y no tiene ni un solo fallo, el volante ni si quiera tiene ninguna marca de desgaste.", 2390, "Vitoria", "https://cdn02.carsforsale.com/3/432928/15322871/978538920.jpg")
    c15 = Coche(m5, "19 Chamade", 1990, 180000, "Gasolina", 80, "Renault 19 Chamade modelo TSE, con 180.000 km. Motor 1.4 gasolina en perfecto estado, kit de distribución nuevo (bomba, correa y tensor), radiador con muy poco tiempo, electro auxiliar, al día de mantenimientos como filtros, aceite, valvulina, anticongelante... Ruedas nuevas, interiores en muy buen estado. Itv recién pasada el 27/12/2019.", 850, "Donostia", "https://www.donocasion.es/img/vehicles/000000295298.jpeg")
    c16 = Coche(m5, "Clio", 2006, 225000, "Gasolina", 70, "Vehículo en muy buen estado con todo el mantenimiento recién hecho, elevalunas eléctricos, cierre centralizado, dirección asistida, aire acondicionado, radio cd, etc, transferido y con 12 meses de garantía", 1800, "Vitoria", "https://drivy.imgix.net/uploads/originals/63f1160136766341880b81a5664ef6d1.jpg")
    c17 = Coche(m5, "R5", 1988, 175000, "Gasolina", 120, "Renault 5 GT Turbo a falta de restaurar ya que lleva tiempo parado, arranca bien, tiene correas y bombos de agua nueva, manguitos de silicona, homologado ancho de vías, asientos homologados, amortiguadores y muelles homologados, se entregan algunos recambios de origen.", 4900, "Donostia", "https://www.autofacil.es/elementosWeb/gestionCajas/AUF/Image/Trasera_1.jpg")
    c18 = Coche(m7, "Land Cruiser", 2004, 259000, "Diesel", 163, "Toyota land cruiser 3.0 d-4d 163cv 4x4 automático con reductora, el más alto de su gama y en perfecto estado. Único propietario. historial de mantenimiento. kilómetros certificados. equipado con: dirección asistida, abs, esp, cierre centralizado, elevalunas eléctricos del. y tras., asientos calefactables con airbags e isofix, espejos abatibles y antideslumbrantes.", 12490, "Bilbao", "https://e00-elmundo.uecdn.es/elmundomotor/imagenes/2004/02/23/1077536287_g.jpg")
    c19 = Coche(m7, "Supra", 1988, 129000, "Gasolina", 238, "Toyota Supra, motor 3.0 6 cilindros TURBO 238CV, IMPECABLE, todo al dia, coche con muy poco uso, Solo dos dueños y los dos personas de adulta edad. Repasado de todo, gran historial en mantenimientos, y perfecto de chapa.", 11000, "Donostia", "https://img.milanuncios.com/fg/3393/33/339333835_4.jpg?VersionId=OwOeOu_Ub.HVQOzS2s33LXeSLvBm2I1U")
    c20 = Coche(m7, "Prius", 2007, 150000, "Híbrido", 112, " Vehículo con distintivo ambiental eco en estado impecable equipado con los extras normales de este modelo", 6090, "Bilbao", "https://www.km77.com/media/fotos/toyota_prius_2006_2093_2.jpg")
    c21 = Coche(m1, "Capri", 1981, 105000, "Gasolina", 160, "Ford Capri 2.8 i 160cv.Vehiculo de colección.Mismo dueño desde 1995.Totalmente de serie.Siempre garaje.Nunca golpes.Interior impecable asi como exterior y motor. Lleva direccion asistida asi como espejos y antena eléctrica.", 12000, "Bilbao", "https://img.milanuncios.com/fg/3684/98/368498133_1.jpg")
    c22 = Coche(m3, "Serie 5", 1998, 287000, "Gasolina", 194, "BMW Serie 5 528i. Al coche se le han hecho bastantes cosas, mucho dinero invertido: Faros Angel Eyes 250€ por cada, Colectores de competicion 700€, Bobinas y Bujias 80€, Pilotos traseros ahumados 100€, Filtros y aceite motor 120€, Pastillas de Freno nuevas 80€, Alternador nuevo 90€, Bateria nueva 125€...", 1490, "Vitoria", "https://img.milanuncios.com/fg/3643/99/364399306_1.jpg")
    c23 = Coche(m2, "Clase C", 1990, 401000, "Diesel", 166, "Todos los libros originales de instrucciones, revisiones, etc. Tiene como equipamiento: Aire acondicionado, dirección asistida, elevalunas eléctricos, espejo eléctrico, cierre centralizado, pintura metalizada (color original negro azulado, similar a gris oscuro), estrella Mercedes extraíble...", 1400, "Bilbao", "https://img.milanuncios.com/fg/3667/20/366720792_2.jpg")
    c24 = Coche(m4, "Coupé", 1989, 250000, "Gasolina", 133, "Buen estado y mantenimiento al dia. Como pega, la tela del techo se esta despegando y el cierre centralizado no funciona. De chapa bien y sin óxidos pero algún rayón en la pintura. Es 2.2 sin catalizar. Se podría entregar con llantas speedline del quattro. Libro de mantenimiento sellado y juego de 4 llaves originales. Estuvo muchos años sin usar aunque arrancándose y moviéndose periódicamente.", 4000, "Vitoria", "https://img.milanuncios.com/fg/2784/49/278449834_2.jpg")
    c25 = Coche(m5, "R21", 1987, 180000, "Gasolina", 80, "Se vende coche clásico en perfecto estado de conservación, sólo un dueño. Se le han hecho todas las revisiones en la Renault incluso la última ya que se le acaba de cambiar todas las correas, la de distribución, tensores, valvulina, aceite motor filtros, líquido de frenos, pastillas y discos de frenos...", 1200, "Vitoria", "https://img.milanuncios.com/fg/3706/93/370693530_2.jpg?VersionId=uXn.6BMqBF8ufPgPR2jY_s.lgDNSo9bi")
    c26 = Coche(m6, "S60", 2005, 249000, "Diesel", 163, "Volvo S60 d5 2.4 163cv impecable de todo, el coche se encuentra en perfecto estado, no tiene ningún desperfecto de interior y de exterior está muy cuidado, extras: cuero , llantas, elevalunas eléctricos , volante multifuncion, radio cd original, control de velocidad , velocidad crucero, sensor de lluvia... consumo de risa, 5,5 litros a los 100km.", 4500, "Donostia", "https://img.milanuncios.com/fg/3612/72/361272098_2.jpg")
    c27 = Coche(m6, "V40", 1998, 143000, "Gasolina", 122, "Precioso Volvo V40 inmaculado, todas las revisiones en volvo, libro de revisiones. Muy cuidado . Elevalunas , dirección asistida, abs , air bag ,aire acondicionado. Perfecto de chapa, perfecto de motor, muy bien de interiores correas de distribuciÓn cambiadas.", 1100, "Donostia", "https://img.milanuncios.com/fg/2852/83/285283572_6.jpg")
    c28 = Coche(m7, "Yaris", 2009, 190000, "Diesel", 129, "Coche en perfecto estado, único propietario, guardado en garaje (pintura original), todas las revisiones en concesionario oficial. Motor diesel, seis velocidades de muy bajo consumo. ITV hasta 10/2021.", 4450, "Donostia", "https://img.milanuncios.com/fg/3706/80/370680781_1.jpg")
    c29 = Coche(m7, "Avensis", 2006, 156000, "Gasolina", 130, "Se vende Toyota Avensis 1.6 16v VVT-i, 130 CV, año 2006, gasolina con 156000 Km. Muy bien cuidado, un único dueño no fumador y siempre en garaje. En muy buen estado de tapicería y pintura, excepto roce en el paragolpes trasero lado derecho y pequeños toques de abrir y cerrar puertas en parkings.", 4500, "Bilbao", "https://img.milanuncios.com/fg/3705/04/370504309_3.jpg")

    session.add(co1)
    session.add(co2)
    session.add(co3)
    session.add(co4)

    session.add(m1)
    session.add(m2)
    session.add(m3)
    session.add(m4)
    session.add(m5)
    session.add(m6)
    session.add(m7)

    session.add(c1)
    session.add(c2)
    session.add(c3)
    session.add(c4)
    session.add(c5)
    session.add(c6)
    session.add(c7)
    session.add(c8)
    session.add(c9)
    session.add(c10)
    session.add(c11)
    session.add(c12)
    session.add(c13)
    session.add(c14)
    session.add(c15)
    session.add(c16)
    session.add(c17)
    session.add(c18)
    session.add(c19)
    session.add(c20)
    session.add(c21)
    session.add(c22)
    session.add(c23)
    session.add(c24)
    session.add(c25)
    session.add(c26)
    session.add(c27)
    session.add(c28)
    session.add(c29)

    session.commit()
    session.close()